CatalogOnline/CatalogOnline/Controllers/AbsenceController.cs
using CatalogOnline.Data;
using CatalogOnline.Models;
using CatalogOnline.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CatalogOnline.Controllers
{
    public class AbsenceController : Controller
    {
        private Repository.AbsenceRepository _absenceRepository;
        private Repository.StudentRepository _studentRepository;
        private Repository.TeacherRepository _teacherRepository;

        public AbsenceController(ApplicationDbContext dbContext)
        {
            _absenceRepository = new Repository.AbsenceRepository(dbContext);
            _studentRepository = new Repository.StudentRepository(dbContext);
            _teacherRepository = new Repository.TeacherRepository(dbContext);
        }

        [Authorize(Roles = "Teacher, Student")]
        // GET: AbsenceController
        public ActionResult Index()
        {
            var absences = _absenceRepository.GetAbsence();
            return View("Index", absences);
        }

        [Authorize(Roles = "Teacher, Student")]
        // GET: AbsenceController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _absenceRepository.GetAbsenceByID(id);
            model = _absenceRepository.NameStudent(model);
            model = _absenceRepository.NameTeacher(model);
            return View("Details", model);
        }

        [Authorize(Roles = "Teacher")]
        // GET: AbsenceController/Create
        public ActionResult Create()
        {
            var students = _studentRepository.GetStudent();
            var teachers = _teacherRepository.GetTeacher();

            var model = new Models.AbsenceModel
            {
                Students = students,
                Teachers = teachers

            };
            return View("Create", model);
        }

        [Authorize(Roles = "Teacher")]
        // POST: AbsenceController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.AbsenceModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _absenceRepository.InsertAbsence(model);

                    return RedirectToAction("Index");
                }

                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    Console.WriteLine($"Validation Error: {error.ErrorMessage}");
                }

                model.Students = _studentRepository.GetStudent();
                model.Teachers = _teacherRepository.GetTeacher();

                return View("Create", model);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                return View("Create", model);
            }
        }

        [Authorize(Roles = "Teacher")]
        // GET: AbsenceController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var students = _studentRepository.GetStudent();
            var teachers = _teacherRepository.GetTeacher();

            var model = _absenceRepository.GetAbsenceByID(id);

            if (model != null)
            {
                model.Students = students;
                model.Teachers = teachers;

                return View("Edit", model);
            }

            return RedirectToAction("Index");
        }

        // POST: AbsenceController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            try
            {
                var model = new AbsenceModel();

                var task = TryUpdateModelAsync(model);
                task.Wait();
                if (task.Result)
                {
                    _absenceRepository.UpdateAbsence(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", id);
                }

            }
            catch
            {
                return RedirectToAction("Index", id);
            }
        }

        [Authorize(Roles = "Teacher")]
        // GET: AbsenceController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _absenceRepository.GetAbsenceByID(id);
            model = _absenceRepository.NameStudent(model);
            model = _absenceRepository.NameTeacher(model);
            return View("Delete", model);
        }

        // POST: AbsenceController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _absenceRepository.DeleteAbsence(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Delete", id);
            }
        }
    }
}

CatalogOnline/CatalogOnline/Controllers/GradeController.cs
using CatalogOnline.Data;
using CatalogOnline.Models;
using CatalogOnline.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CatalogOnline.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class GradeController : Controller
    {
        private Repository.GradeRepository _gradeRepository;
        private Repository.StudentRepository _studentRepository;
        private Repository.TeacherRepository _teacherRepository;

        public GradeController(ApplicationDbContext dbContext)
        {
            _gradeRepository = new Repository.GradeRepository(dbContext);
            _studentRepository = new Repository.StudentRepository(dbContext);
            _teacherRepository = new Repository.TeacherRepository(dbContext);
        }

        [Authorize(Roles = "Teacher, Student")]
        // GET: GradeController
        public ActionResult Index()
        {
            var grades = _gradeRepository.GetGrade();
            return View("Index", grades);
        }

        [Authorize(Roles = "Teacher")]
        // GET: GradeController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _gradeRepository.GetGradeByID(id);
            model = _gradeRepository.NameStudent(model);
            model = _gradeRepository.NameTeacher(model);
            return View("Details", model);
        }

        [Authorize(Roles = "Teacher")]
        // GET: GradeController/Create
        public ActionResult Create()
        {
            var students = _studentRepository.GetStudent();
            var teachers = _teacherRepository.GetTeacher();

            var model = new Models.GradeModel
            {
                Students = students,
                Teachers = teachers

            };
            return View("Create", model);
        }

        // POST: GradeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.GradeModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _gradeRepository.InsertGrade(model);

                    return RedirectToAction("Index");
                }

                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    Console.WriteLine($"Validation Error: {error.ErrorMessage}");
                }

                model.Students = _studentRepository.GetStudent();
                model.Teachers = _teacherRepository.GetTeacher();

                return View("Create", model);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");

                return View("Create", model);
            }
        }


        [Authorize(Roles = "Teacher")]
        // GET: GradeController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var students = _studentRepository.GetStudent();
            var teachers = _teacherRepository.GetTeacher();

            var model = _gradeRepository.GetGradeByID(id);

            if (model != null)
            {
                model.Students = students;
                model.Teachers = teachers;

                return View("Edit", model);
            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Teacher")]
        // POST: GradeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            try
            {
                var model = new GradeModel();

                var task = TryUpdateModelAsync(model);
                task.Wait();
                if (task.Result)
                {
                    _gradeRepository.UpdateGrade(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", id);
                }

            }
            catch
            {
                return RedirectToAction("Index", id);
            }
        }

        [Authorize(Roles = "Teacher")]
        // GET: GradeController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _gradeRepository.GetGradeByID(id);
            model = _gradeRepository.NameStudent(model);
            model = _gradeRepository.NameTeacher(model);
            return View("Delete", model);
        }

        // POST: GradeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _gradeRepository.DeleteGrade(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Delete", id);
            }
        }
    }
}

CatalogOnline/CatalogOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CatalogOnline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CatalogOnline.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://icons.iconarchive.com/icons/hopstarter/book/256/Moleskine-Blue-Book-icon.png" style="width: 50px; height: 50px;" />
                </a>                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Absence" asp-action="Index">Absence</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Grade" asp-action="Index">Grade</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>